/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConversationsController_getConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConversationsController_getConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PromptsController_getPrompts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PromptsController_getPrompt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PoliciesController_getPolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PoliciesController_getPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConversationEntity: {
            /**
             * @description The UUID of the conversation
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description The title of the conversation
             * @example Example Conversation
             */
            title: string;
            /**
             * @description The UUID of the user
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            user_id: string;
            /**
             * @description The creation date of the conversation
             * @example 2023-01-01T00:00:00.000Z
             */
            created: string;
            /**
             * @description The update date of the conversation
             * @example 2023-01-01T00:00:00.000Z
             */
            updated: string;
        };
        PaginatedConversationsResponseDTO: {
            /** @description The conversations */
            conversations: components["schemas"]["ConversationEntity"][];
            /** @description The total number of conversations */
            total: number;
            /** @description The page number */
            page: number;
            /** @description The limit number */
            limit: number;
            /** @description The offset number */
            offset: number;
        };
        LLMResponseEntity: {
            /**
             * Format: uuid
             * @description The UUID of the entity
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description The creation date of the entity
             * @example 2023-01-01T00:00:00.000Z
             */
            created: string;
            /**
             * @description The update date of the entity
             * @example 2023-01-01T00:00:00.000Z
             */
            updated: string;
            /**
             * Format: uuid
             * @description The UUID of the conversation
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            conversation_id: string;
            /**
             * Format: uuid
             * @description The UUID of the policy
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            policy_id: string;
            /**
             * @description The risk score of the entity
             * @example 0
             */
            risk_score: number;
            /**
             * @description The action of the entity
             * @example none
             * @enum {string}
             */
            action: "none" | "blocked";
            /**
             * Format: uuid
             * @description The UUID of the prompt
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            prompt_id: string;
            /**
             * @description The completion date of the LLM response
             * @example 2023-01-01T00:00:00.000Z
             */
            completed_at: string;
            /**
             * @description The model of the LLM response
             * @example gpt-4.1-2025-04-14
             */
            model: string;
            /**
             * @description The output of the LLM response
             * @example {
             *       "type": "message",
             *       "content": [
             *         {
             *           "type": "output_text",
             *           "text": "Here's how to implement authentication..."
             *         }
             *       ]
             *     }
             */
            output: {
                [key: string]: unknown;
            } | null;
        };
        PromptEntity: {
            /**
             * Format: uuid
             * @description The UUID of the entity
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description The creation date of the entity
             * @example 2023-01-01T00:00:00.000Z
             */
            created: string;
            /**
             * @description The update date of the entity
             * @example 2023-01-01T00:00:00.000Z
             */
            updated: string;
            /**
             * Format: uuid
             * @description The UUID of the conversation
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            conversation_id: string;
            /**
             * Format: uuid
             * @description The UUID of the policy
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            policy_id: string;
            /**
             * @description The risk score of the entity
             * @example 0
             */
            risk_score: number;
            /**
             * @description The action of the entity
             * @example none
             * @enum {string}
             */
            action: "none" | "blocked";
            /**
             * @description The text of the prompt
             * @example How do I implement authentication?
             */
            text: string;
            /** @description The LLM responses of the prompt */
            llm_responses?: components["schemas"]["LLMResponseEntity"][];
        };
        PaginatedPromptsResponseDTO: {
            /** @description The prompts */
            prompts: components["schemas"]["PromptEntity"][];
            /** @description The total number of prompts */
            total: number;
            /** @description The page number */
            page: number;
            /** @description The limit number */
            limit: number;
            /** @description The offset number */
            offset: number;
        };
        UserEntity: {
            /**
             * Format: uuid
             * @description The UUID of the user
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description The name of the user
             * @example John Doe
             */
            name: string;
            /**
             * @description The email of the user
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description The VIP status of the user
             * @example 1
             */
            vip: number;
            /**
             * @description The creation date of the user
             * @example 2023-01-01T00:00:00.000Z
             */
            created: string;
            /**
             * @description The update date of the user
             * @example 2023-01-01T00:00:00.000Z
             */
            updated: string;
        };
        PaginatedUsersResponseDTO: {
            /** @description The users */
            users: components["schemas"]["UserEntity"][];
            /** @description The total number of users */
            total: number;
            /** @description The page number */
            page: number;
            /** @description The limit number */
            limit: number;
            /** @description The offset number */
            offset: number;
        };
        PolicyEntity: {
            /**
             * Format: uuid
             * @description The UUID of the policy
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description The name of the policy
             * @example Global AI Policy
             */
            policy_name: string;
            /**
             * @description The version of the policy
             * @example 1523
             */
            policy_version: number;
            /**
             * @description The creation date of the policy
             * @example 2023-01-01T00:00:00.000Z
             */
            created: string;
            /**
             * @description The update date of the policy
             * @example 2023-01-01T00:00:00.000Z
             */
            updated: string;
        };
        PaginatedPoliciesResponseDto: {
            /** @description List of policies */
            policies: components["schemas"]["PolicyEntity"][];
            /**
             * @description Total number of items
             * @example 100
             */
            total: number;
            /**
             * @description Current page number
             * @example 1
             */
            page: number;
            /**
             * @description Items per page
             * @example 10
             */
            limit: number;
            /**
             * @description Offset for pagination
             * @example 0
             */
            offset: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ConversationsController_getConversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conversations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedConversationsResponseDTO"];
                };
            };
        };
    };
    ConversationsController_getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conversation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationEntity"];
                };
            };
        };
    };
    PromptsController_getPrompts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of prompts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPromptsResponseDTO"];
                };
            };
        };
    };
    PromptsController_getPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The prompt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptEntity"];
                };
            };
        };
    };
    UsersController_getUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUsersResponseDTO"];
                };
            };
        };
    };
    UsersController_getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    PoliciesController_getPolicies: {
        parameters: {
            query?: {
                /** @description The limit of the items per page */
                limit?: number;
                /** @description The page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of policies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPoliciesResponseDto"];
                };
            };
        };
    };
    PoliciesController_getPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyEntity"];
                };
            };
        };
    };
}
